/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <blinker.h>
#include <sha_256.h>
#include <img_header.h>

#define APP_BASE 0x08020200u
#define APP_HEADER_ADDR 0x08020000u

/* System Control Block */
#define SCB_VTOR        (*(volatile uint32_t *)0xE000ED08u)

/* SysTick */
#define SYSTICK_CTRL    (*(volatile uint32_t *)0xE000E010u)
#define SYSTICK_LOAD    (*(volatile uint32_t *)0xE000E014u)
#define SYSTICK_VAL     (*(volatile uint32_t *)0xE000E018u)

typedef void (*app_entry_t)(void);

void refuse()
{
	set_red();
	for (;;) { }
}

static void jump_to_app(uint32_t base)
{
    uint32_t msp   = *(volatile uint32_t *)(base);      /* vector[0] */
    uint32_t entry = *(volatile uint32_t *)(base + 4);  /* vector[1] */

    /* mask all interrupts */
    __asm volatile ("cpsid i" ::: "memory");

    /* stop SysTick so it can't fire into a stale vector table */
    SYSTICK_CTRL = 0;
    SYSTICK_LOAD = 0;
    SYSTICK_VAL  = 0;

    /* point the vector table at the app */
    SCB_VTOR = base;

    /* adopt the app's stack pointer */
    __asm volatile ("msr msp, %0" :: "r" (msp) : );

    /* flush pipeline so the new VTOR/MSP take effect before the branch */
    __asm volatile ("dsb" ::: "memory");
    __asm volatile ("isb" ::: "memory");

    ((app_entry_t)entry)();   /* never returns */
}

int main(void)
{
	gpio_init();

	const img_header_t *hdr = (const img_header_t *)APP_HEADER_ADDR;
	const uint8_t *body     = (const uint8_t *)APP_BODY_ADDR;

	if(hdr->magic != IMG_MAGIC)
	{
		refuse();
	}

	if (hdr->img_len == 0 || hdr->img_len > APP_SLOT_SIZE - IMG_HEADER_SIZE)
	{
		refuse();
	}

	sha256_ctx ctx;
	uint8_t computed[32];

	sha256_init(&ctx);
	sha256_update(&ctx, body, hdr->img_len);
	sha256_final(&ctx, computed);

	if (memcmp(computed, hdr->hash, 32) != 0)
	{
		refuse();
	}

	gpio_blink();
	jump_to_app(APP_BODY_ADDR);

	for (;;) { }

	return 0;

}
